/* soapqqOnlineWebServiceSoapProxy.cpp
   Generated by gSOAP 2.8.67 for .\qqCheckOnline.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapqqOnlineWebServiceSoapProxy.h"

SOAP_NMAC struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"ns1", "http://WebXml.com.cn/", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };

qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	qqOnlineWebServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy(const qqOnlineWebServiceSoapProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	qqOnlineWebServiceSoapProxy_init(_soap->imode, _soap->omode);
}

qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy(const char *endpoint)
{	this->soap = soap_new();
	this->soap_own = true;
	qqOnlineWebServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	qqOnlineWebServiceSoapProxy_init(iomode, iomode);
}

qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy(const char *endpoint, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	qqOnlineWebServiceSoapProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	qqOnlineWebServiceSoapProxy_init(imode, omode);
}

qqOnlineWebServiceSoapProxy::~qqOnlineWebServiceSoapProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void qqOnlineWebServiceSoapProxy::qqOnlineWebServiceSoapProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
//	static const struct Namespace namespaces[] = {
//        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
//        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
//        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
//        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
//        {"ns1", "http://WebXml.com.cn/", NULL, NULL},
//        {NULL, NULL, NULL, NULL}
//    };
	soap_set_namespaces(this->soap, namespaces);
}

qqOnlineWebServiceSoapProxy *qqOnlineWebServiceSoapProxy::copy()
{	qqOnlineWebServiceSoapProxy *dup = SOAP_NEW_UNMANAGED(qqOnlineWebServiceSoapProxy);
	if (dup)
	{	soap_done(dup->soap);
		soap_copy_context(dup->soap, this->soap);
	}
	return dup;
}

qqOnlineWebServiceSoapProxy& qqOnlineWebServiceSoapProxy::operator=(const qqOnlineWebServiceSoapProxy& rhs)
{	if (this->soap != rhs.soap)
	{	if (this->soap_own)
			soap_free(this->soap);
		this->soap = rhs.soap;
		this->soap_own = false;
		this->soap_endpoint = rhs.soap_endpoint;
	}
	return *this;
}

void qqOnlineWebServiceSoapProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void qqOnlineWebServiceSoapProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	qqOnlineWebServiceSoapProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void qqOnlineWebServiceSoapProxy::soap_noheader()
{	this->soap->header = NULL;
}

::SOAP_ENV__Header *qqOnlineWebServiceSoapProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *qqOnlineWebServiceSoapProxy::soap_fault()
{	return this->soap->fault;
}

const char *qqOnlineWebServiceSoapProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *qqOnlineWebServiceSoapProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int qqOnlineWebServiceSoapProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int qqOnlineWebServiceSoapProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void qqOnlineWebServiceSoapProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void qqOnlineWebServiceSoapProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *qqOnlineWebServiceSoapProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int qqOnlineWebServiceSoapProxy::qqCheckOnline(const char *endpoint, const char *soap_action, _ns1__qqCheckOnline *ns1__qqCheckOnline, _ns1__qqCheckOnlineResponse &ns1__qqCheckOnlineResponse)
{
	struct __ns1__qqCheckOnline soap_tmp___ns1__qqCheckOnline;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/qqCheckOnline";
	soap_tmp___ns1__qqCheckOnline.ns1__qqCheckOnline = ns1__qqCheckOnline;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__qqCheckOnline(soap, &soap_tmp___ns1__qqCheckOnline);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__qqCheckOnline(soap, &soap_tmp___ns1__qqCheckOnline, "-ns1:qqCheckOnline", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__qqCheckOnline(soap, &soap_tmp___ns1__qqCheckOnline, "-ns1:qqCheckOnline", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__qqCheckOnlineResponse*>(&ns1__qqCheckOnlineResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__qqCheckOnlineResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__qqCheckOnlineResponse.soap_get(soap, "ns1:qqCheckOnlineResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int qqOnlineWebServiceSoapProxy::qqCheckOnline_(const char *endpoint, const char *soap_action, _ns1__qqCheckOnline *ns1__qqCheckOnline, _ns1__qqCheckOnlineResponse &ns1__qqCheckOnlineResponse)
{
	struct __ns1__qqCheckOnline_ soap_tmp___ns1__qqCheckOnline_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://www.webxml.com.cn/webservices/qqOnlineWebService.asmx";
	if (soap_action == NULL)
		soap_action = "http://WebXml.com.cn/qqCheckOnline";
	soap_tmp___ns1__qqCheckOnline_.ns1__qqCheckOnline = ns1__qqCheckOnline;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__qqCheckOnline_(soap, &soap_tmp___ns1__qqCheckOnline_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__qqCheckOnline_(soap, &soap_tmp___ns1__qqCheckOnline_, "-ns1:qqCheckOnline", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__qqCheckOnline_(soap, &soap_tmp___ns1__qqCheckOnline_, "-ns1:qqCheckOnline", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns1__qqCheckOnlineResponse*>(&ns1__qqCheckOnlineResponse)) // NULL ref?
		return soap_closesock(soap);
	ns1__qqCheckOnlineResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__qqCheckOnlineResponse.soap_get(soap, "ns1:qqCheckOnlineResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
